#spring:
#  datasource:
#    drivaerClassName: org.h2.Driver
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELEY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#

spring:
  datasource:
    drivaerClassName: org.h2.Driver
    url: jdbc:h2:file:c:/tmp/testdb
    username: sa
    password:
